Repository miacheng2/CITS5206-capstone, pull requests merged in 2024-09, with the labels that each got.

#63 Fix "Invalid token" error
  Front_end/src/api.js
  Front_end/src/components/ChangePassword.js
  Front_end/src/components/styles/AdminUserManagement.module.css
  Front_end/src/components/styles/ChangePassword.module.css
  myproject/myproject/settings.py
Labels: enhancement

#68 Fix two bugs caused by Xia and implementing token
  Front_end/src/components/CheckEventHistory.js
  Front_end/src/components/EventDetailsModal.js
  Front_end/src/components/EventList.js
  myproject/events/migrations/0002_remove_user_is_admin_remove_user_user_type_and_more.py
  myproject/events/migrations/0003_remove_user_groups_remove_user_is_superuser_and_more.py
  myproject/events/migrations/0004_activity_event_activities_volunteerpoints_activity.py
  myproject/events/migrations/0005_remove_teammember_name_teammember_first_name_and_more.py
  myproject/events/migrations/0006_teammember_mobile.py
  myproject/events/migrations/0007_team_last_modified_date_team_team_leader_and_more.py
  myproject/events/migrations/0008_alter_team_name.py
  myproject/events/migrations/0009_alter_team_description.py
  myproject/events/migrations/0010_alter_team_description.py
  myproject/events/migrations/0011_remove_team_last_modified_date_and_more.py
  myproject/events/migrations/0012_team_last_modified_date_team_team_leader_and_more.py
Labels: bug

#70 Brand
  myproject/events/migrations/0002_remove_user_is_admin_remove_user_user_type_and_more.cpython-312.pyc
  myproject/events/migrations/0002_remove_user_is_admin_remove_user_user_type_and_more.py
  myproject/events/migrations/0003_remove_user_groups_remove_user_is_superuser_and_more.cpython-312.pyc
  myproject/events/migrations/0003_remove_user_groups_remove_user_is_superuser_and_more.py
  myproject/events/migrations/0004_activity_event_activities_volunteerpoints_activity.cpython-312.pyc
  myproject/events/migrations/0004_activity_event_activities_volunteerpoints_activity.py
  myproject/events/migrations/0005_remove_teammember_name_teammember_first_name_and_more.cpython-312.pyc
  myproject/events/migrations/0005_remove_teammember_name_teammember_first_name_and_more.py
  myproject/events/migrations/0005_volunteerteam_member.cpython-312.pyc
  myproject/events/migrations/0006_teammember_mobile.cpython-312.pyc
  myproject/events/migrations/0006_teammember_mobile.py
  myproject/events/migrations/0007_team_last_modified_date_team_team_leader_and_more.cpython-312.pyc
  myproject/events/migrations/0007_team_last_modified_date_team_team_leader_and_more.py
  myproject/events/migrations/0008_alter_team_name.cpython-312.pyc
  myproject/events/migrations/0008_alter_team_name.py
  myproject/events/migrations/0009_alter_team_description.cpython-312.pyc
  myproject/events/migrations/0009_alter_team_description.py
  myproject/events/migrations/0010_alter_team_description.cpython-312.pyc
  myproject/events/migrations/0010_alter_team_description.py
  myproject/events/migrations/0011_remove_team_last_modified_date_and_more.cpython-312.pyc
  myproject/events/migrations/0011_remove_team_last_modified_date_and_more.py
  myproject/events/migrations/0012_team_last_modified_date_team_team_leader_and_more.cpython-312.pyc
  myproject/events/migrations/0012_team_last_modified_date_team_team_leader_and_more.py
Labels: bug

#77 Change storage, calculation and display for hours and points
  Front_end/src/components/AddVolunteerPoints.js
  Front_end/src/components/MemberVolunteerHistory.js
  myproject/events/migrations/0013_alter_volunteerpoints_hours_and_more.py
  myproject/events/models.py
  myproject/events/views.py
  myproject/myproject/urls.py
Labels: bug, enhancement
